apiVersion: v1
kind: Service
metadata:
  name: eleanor-employees-ms-service
  namespace: eleanor
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: eleanor-employees-ms-service
  type: ClusterIP
