apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: eleanor-employees-hpa
  namespace: eleanor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eleanor-employees-ms
  minReplicas: 1
  maxReplicas: 15
  targetCPUUtilizationPercentage: 80